[package]
name = "rthm"
version = "0.1.0"
authors = ["Aaron Kofsky <a2aarontothe2@gmail.com>"]
edition = "2018"

[dependencies]
# This is version 0.6.0-rc1 of ggez
ggez = { git = "https://github.com/a2aaron/ggez", rev = "359442b7869b580e8dae8435226e3888617ea5e8" } # { path = "ggez" } # "0.5.1"

rand = "0.8.0"
derive_more = "0.99.0"
rodio = "0.14.0"
cgmath = "0.18.0"
